ALTER TABLE tour_packages 
ADD COLUMN IF NOT EXISTS show_on_home BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS home_order INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS show_on_araku BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS show_on_lambasingi BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS show_on_vanjangi BOOLEAN DEFAULT false;
